# Generated by Django 4.1.2 on 2022-10-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartegory_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('cart_image', models.ImageField(blank=True, upload_to='photos/cartgories')),
            ],
            options={
                'verbose_name': 'Cartegory',
                'verbose_name_plural': 'Cartegories',
            },
        ),
    ]
