# Generated by Django 4.1.2 on 2022-10-11 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartegory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('product_description', models.TextField(blank=True, max_length=555)),
                ('price', models.IntegerField()),
                ('images', models.ImageField(blank=True, upload_to='photos/product')),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('cartegory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cartegory.cartegory')),
            ],
        ),
    ]
