# Generated by Django 4.1.2 on 2022-10-11 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartegory', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cartegory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cartegory.cartegory'),
            preserve_default=False,
        ),
    ]
